/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.View.Console;

import java.awt.event.ActionEvent;
import myproject.Model.Common.Console.ConsoleManager;
import myproject.Model.Common.Listeners.ClientConsoleManagerListener;
import myproject.Model.Server.Client2Server;
import myproject.View.Common.UniversalMainFrame;

/**
 *
 * @author BotNaEasyEnv
 */
public class ConsolePanel extends javax.swing.JPanel {

    private ConsoleManager manager;
    /**
     * Creates new form ConsolePanel
     */
    public ConsolePanel(Client2Server c2s) {
        initComponents();
        manager = new ConsoleManager(c2s);
        listener();
    }
    
    private void listener(){
        manager.getC2S().addClientConsoleManagerListener(new ClientConsoleManagerListener() {
            @Override
            public void onGetAnswer(ActionEvent e) {
                showOn(e.getActionCommand());
            }
        });
    }
    
    private void showOn(String response){
        String message = chatTA.getText();
        String result = message + "\n" + response;
        chatTA.setText(result);
    }
    private void sendExe(){
        String toExe = messageField.getText();
        if(toExe.isEmpty()){
            UniversalMainFrame.main.showInfoDialog("Empty command");
            return;
        }
        showOn(messageField.getText());
        messageField.setText("");
        manager.sendExecuteRequest(toExe.split(" "));
    }
    
    private void clear(){
        chatTA.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatTA = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        messageField = new javax.swing.JTextField();
        executeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        chatTA.setEditable(false);
        chatTA.setColumns(20);
        chatTA.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        chatTA.setRows(5);
        jScrollPane2.setViewportView(chatTA);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        messageField.setPreferredSize(new java.awt.Dimension(345, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.1;
        jPanel2.add(messageField, gridBagConstraints);

        executeButton.setText("execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 15;
        gridBagConstraints.gridy = 0;
        jPanel2.add(executeButton, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        clearButton.setText("clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel3.add(clearButton, new java.awt.GridBagConstraints());

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        sendExe();
    }//GEN-LAST:event_executeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatTA;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton executeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messageField;
    // End of variables declaration//GEN-END:variables
}
