/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.View.FileManager;

/**
 *
 * @author BotNaEasyEnv
 */
public class GetFileNamePanel extends javax.swing.JPanel {

    /**
     * Creates new form GetFileNamePanel
     */
    public GetFileNamePanel() {
        initComponents();
    }
    
    public String getText(){
       return  textField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        textField.setPreferredSize(new java.awt.Dimension(200, 30));
        add(textField, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
