/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.View.Client;

import myproject.Model.Client.DuplexClient;


/**
 *
 * @author BotNaEasyEnv
 */
public class ClientPanel extends javax.swing.JPanel {

   
    
    private DuplexClient client;
    /**
     * Creates new form ClientPanel
     */
    public ClientPanel() {
        initComponents();
        initClient();
        chatConfig();
    }
    private void chatConfig(){
        chatTA.setEditable(false);
        chatTA.setEnabled(true);
    }
    
    private void initClient(){
        client = new DuplexClient(this);
        ipTF.setText(client.getHOST());
    }
    
    public void updateForMessage(String message){
        chatTA.append("\n"+message);
    }
    
    private void send(){
        String message = messageField.getText();
        try{
            client.sendMessage(message);
            messageField.setText("");
            chatTA.append("\n"+message);
        }catch(Exception e){
            chatTA.append("\nConnection error");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        ipTF = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chatTA = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        messageField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridBagLayout());

        ipTF.setMinimumSize(new java.awt.Dimension(250, 20));
        ipTF.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel3.add(ipTF, new java.awt.GridBagConstraints());

        connectButton.setText("connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });
        jPanel3.add(connectButton, new java.awt.GridBagConstraints());

        add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        chatTA.setColumns(20);
        chatTA.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        chatTA.setRows(5);
        chatTA.setEnabled(false);
        jScrollPane2.setViewportView(chatTA);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        messageField.setPreferredSize(new java.awt.Dimension(345, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.1;
        jPanel2.add(messageField, gridBagConstraints);

        sendButton.setText("send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        jPanel2.add(sendButton, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        send();
    }//GEN-LAST:event_sendButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        client.setServer(ipTF.getText());
        client.tryToConnect();
    }//GEN-LAST:event_connectButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chatTA;
    private javax.swing.JButton connectButton;
    private javax.swing.JTextField ipTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messageField;
    private javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
