/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.View.Common;

import java.io.File;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import myproject.Model.Common.ExtendedComponents.ExtendedJTable;
import myproject.Model.Common.ExtendedComponents.ExtendedJTree;
import myproject.Model.Common.FileManager.Client2ServerFileManager;
import myproject.Model.Common.FileManager.TreeModels.FileTreeNode;
import myproject.Model.Common.TableModels.FilesTableModel;

/**
 *
 * @author BotNaEasyEnv
 */
public class FilesPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilesPanel
     */
    private ExtendedJTable table;
    private FilesTableModel model;
    private Client2ServerFileManager manager;
    private ExtendedJTree tree;
    
    public FilesPanel(Client2ServerFileManager manager, ExtendedJTree tree) {
        this.manager = manager;
        this.tree = tree;
        initComponents();
        initTable();
    }
    private void initTable(){
        table = new ExtendedJTable();
        fileTablePanel.add(new JScrollPane(table));
    }
    
    public void reload(){
        table.setModel(model);
    }

    public ExtendedJTable getTable() {
        return table;
    }

    public void setTable(ExtendedJTable table) {
        this.table = table;
    }

    public FilesTableModel getModel() {
        return model;
    }

    public void setModel(FilesTableModel model) {
        this.model = model;
        reload();
    }
    
    public JProgressBar getProgressBar(){
        return progressField;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        progressPanel = new javax.swing.JPanel();
        progressField = new javax.swing.JProgressBar();
        controlsPanel = new javax.swing.JPanel();
        sendFileButton = new javax.swing.JButton();
        createDirectoryButton = new javax.swing.JButton();
        downloadDirectoryButton = new javax.swing.JButton();
        fileTablePanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        progressPanel.setLayout(new java.awt.BorderLayout());
        progressPanel.add(progressField, java.awt.BorderLayout.CENTER);

        add(progressPanel, java.awt.BorderLayout.PAGE_END);

        controlsPanel.setLayout(new java.awt.GridBagLayout());

        sendFileButton.setText("Send file");
        sendFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFileButtonActionPerformed(evt);
            }
        });
        controlsPanel.add(sendFileButton, new java.awt.GridBagConstraints());

        createDirectoryButton.setText("Create directory");
        createDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDirectoryButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        controlsPanel.add(createDirectoryButton, gridBagConstraints);

        downloadDirectoryButton.setText("Download directory");
        downloadDirectoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadDirectoryButtonActionPerformed(evt);
            }
        });
        controlsPanel.add(downloadDirectoryButton, new java.awt.GridBagConstraints());

        add(controlsPanel, java.awt.BorderLayout.PAGE_START);

        fileTablePanel.setLayout(new java.awt.BorderLayout());
        add(fileTablePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void sendFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendFileButtonActionPerformed

    private void createDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDirectoryButtonActionPerformed
        FileTreeNode node = (FileTreeNode) tree.getSelectedNode();
        File toCreate = new File(node.getValue().getAbsolutePath()+"\\folder");
        manager.createDirectoryMessage(toCreate, tree.getSelectionPath());
    }//GEN-LAST:event_createDirectoryButtonActionPerformed

    private void downloadDirectoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadDirectoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_downloadDirectoryButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JButton createDirectoryButton;
    private javax.swing.JButton downloadDirectoryButton;
    private javax.swing.JPanel fileTablePanel;
    private javax.swing.JProgressBar progressField;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JButton sendFileButton;
    // End of variables declaration//GEN-END:variables
}
