/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.View.Common;

import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import myproject.Model.Common.ExtendedComponents.ExtendedJTable;
import myproject.Model.Common.TableModels.FilesTableModel;

/**
 *
 * @author BotNaEasyEnv
 */
public class FilesPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilesPanel
     */
    private ExtendedJTable table;
    private FilesTableModel model;
    
    public FilesPanel() {
        initComponents();
        initTable();
    }
    private void initTable(){
        table = new ExtendedJTable();
        fileTablePanel.add(new JScrollPane(table));
    }
    
    public void reload(){
        table.setModel(model);
    }

    public ExtendedJTable getTable() {
        return table;
    }

    public void setTable(ExtendedJTable table) {
        this.table = table;
    }

    public FilesTableModel getModel() {
        return model;
    }

    public void setModel(FilesTableModel model) {
        this.model = model;
        reload();
    }
    
    public JProgressBar getProgressBar(){
        return progressField;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        progressPanel = new javax.swing.JPanel();
        progressField = new javax.swing.JProgressBar();
        controlsPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        fileTablePanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        progressPanel.setLayout(new java.awt.BorderLayout());
        progressPanel.add(progressField, java.awt.BorderLayout.CENTER);

        add(progressPanel, java.awt.BorderLayout.PAGE_END);

        controlsPanel.setLayout(new java.awt.GridBagLayout());

        jButton3.setText("Send file");
        controlsPanel.add(jButton3, new java.awt.GridBagConstraints());

        jButton2.setText("Create directory");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        controlsPanel.add(jButton2, gridBagConstraints);

        jButton1.setText("Download directory");
        controlsPanel.add(jButton1, new java.awt.GridBagConstraints());

        add(controlsPanel, java.awt.BorderLayout.PAGE_START);

        fileTablePanel.setLayout(new java.awt.BorderLayout());
        add(fileTablePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JPanel fileTablePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JProgressBar progressField;
    private javax.swing.JPanel progressPanel;
    // End of variables declaration//GEN-END:variables
}
