/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.View.Common;

import java.awt.BorderLayout;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import myproject.View.Client.ClientPanel;
import myproject.View.Server.ServerPanel;

/**
 *
 * @author BotNaEasyEnv
 */
public class UniversalMainFrame extends javax.swing.JFrame {
    
    public static UniversalMainFrame main;
    private static JDesktopPane desktop;
    /**
     * Creates new form UniversalFrame
     */
    public UniversalMainFrame() {
        initComponents();
        main = this;
        desktop = new JDesktopPane();
        main.setContentPane(main.getDesktop());
    }
    private void initPanel(String arg){
        this.setTitle(arg);
        
        if(arg.equals("server")){
            //mainPanel.add(new ServerPanel());
            showInInternalFrame("Server", new ServerPanel(), false);
            showInInternalFrame("Client", new ClientPanel(), true);
        }else if(arg.equals("client")){
            //mainPanel.add(new ClientPanel());
            showInInternalFrame("Client", new ClientPanel(), false);
        }
    }
    
    private static JDesktopPane getDesktop(){
        return desktop;
    }
    
    public static void showInInternalFrame(String frameTitle, JPanel panel, boolean isCloseable){
        JInternalFrame frame = createFrame(frameTitle, panel, isCloseable);
        if(!checkIsEnabled(frame)){
            main.getDesktop().add(frame);
            frame.toFront();
        }
    }
    
    public static void showInInternalFrame(JInternalFrame frame){
        if(!checkIsEnabled(frame)){
            main.getDesktop().add(frame);
            frame.toFront();
        }
    }
    
    private static boolean checkIsEnabled(JInternalFrame frame){
         Component[] comps = main.getDesktop().getComponents();
         for(int i=0;i<comps.length;i++){
             if(((JInternalFrame)comps[i]).getTitle().equals(frame.getTitle())){
                 ((JInternalFrame)comps[i]).toFront();
                 return true;
             }
         }
         return false;
    }
    
    private static JInternalFrame createFrame(String title, JPanel panel, boolean isCloseable){
        JInternalFrame frame = new JInternalFrame(title);
        frame.add(panel);
        frame.setResizable(true);
        frame.setClosable(isCloseable);
        frame.setMaximizable(true);
        //frame.setIconifiable(true);
        frame.setVisible(true);
        frame.pack();
        return frame;
    }
    
    public void showErrorDialog(String message){
        JOptionPane.showMessageDialog(main, message, "Warning!", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        mainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               UniversalMainFrame mainFrame= new UniversalMainFrame();
               mainFrame.initPanel(args[0]);
               mainFrame.setSize(1000, 600);
               mainFrame.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
