/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.View.Common;

/**
 *
 * @author BotNaEasyEnv
 */
public class UniversalInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form CommonInternalFrame
     */
    public UniversalInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inPanel = new javax.swing.JPanel();

        inPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(inPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel inPanel;
    // End of variables declaration//GEN-END:variables
}
