/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject.View.Common;

import javax.swing.JOptionPane;
import myproject.View.Client.ClientPanel;
import myproject.View.Server.ServerPanel;

/**
 *
 * @author BotNaEasyEnv
 */
public class UniversalMainFrame extends javax.swing.JFrame {
    
    public static UniversalMainFrame main;

    /**
     * Creates new form UniversalFrame
     */
    public UniversalMainFrame() {
        initComponents();
        main = this;
    }
    private void initPanel(String arg){
        this.setTitle(arg);
        if(arg.equals("server")){
            mainPanel.add(new ServerPanel());
        }else if(arg.equals("client")){
            mainPanel.add(new ClientPanel());
        }
    }
    
    public static void showErrorDialog(String message){
        JOptionPane.showMessageDialog(main, message, "Warning!", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        mainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               UniversalMainFrame mainFrame= new UniversalMainFrame();
               mainFrame.initPanel(args[0]);
               mainFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
